package generate

import (
	"fmt"
	"strings"

	"github.com/EdgarOrtegaRamirez/makegen/internal/detect"
)

// Makefile generates Makefile content for the detected project.
func Makefile(project *detect.Project, name string) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by makegen\n")
	b.WriteString(fmt.Sprintf("# Project: %s (%s)\n", name, project.Type))
	if len(project.SubTypes) > 1 {
		b.WriteString(fmt.Sprintf("# Types: %s\n", strings.Join(typeStrings(project.SubTypes), ", ")))
	}
	b.WriteString(fmt.Sprintf("# https://github.com/EdgarOrtegaRamirez/makegen\n"))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("PROJECT_NAME ?= %s\n", sanitizeName(name)))
	b.WriteString("\n")

	// If multi-type, generate for each
	seen := make(map[detect.Type]bool)
	for _, t := range project.SubTypes {
		if seen[t] {
			continue
		}
		seen[t] = true
		gen, err := generateForType(t, project)
		if err != nil {
			return "", err
		}
		b.WriteString(gen)
		b.WriteString("\n")
	}

	// Global targets
	b.WriteString(".PHONY: all build test clean lint format help release install audit\n")
	b.WriteString("\n")

	// If single type, add aliases
	if len(project.SubTypes) == 1 {
		b.WriteString("all: build\n")
		b.WriteString("build: build-" + string(project.SubTypes[0]) + "\n")
		b.WriteString("test: test-" + string(project.SubTypes[0]) + "\n")
		b.WriteString("clean: clean-" + string(project.SubTypes[0]) + "\n")
		b.WriteString("lint: lint-" + string(project.SubTypes[0]) + "\n")
		b.WriteString("format: format-" + string(project.SubTypes[0]) + "\n")
	} else {
		// Multi-type: run all
		b.WriteString("all: build\n")
		b.WriteString("build:")
		for _, t := range project.SubTypes {
			b.WriteString(" build-" + string(t))
		}
		b.WriteString("\n")
		b.WriteString("test:")
		for _, t := range project.SubTypes {
			b.WriteString(" test-" + string(t))
		}
		b.WriteString("\n")
		b.WriteString("clean:")
		for _, t := range project.SubTypes {
			b.WriteString(" clean-" + string(t))
		}
		b.WriteString("\n")
		b.WriteString("lint:")
		for _, t := range project.SubTypes {
			b.WriteString(" lint-" + string(t))
		}
		b.WriteString("\n")
		b.WriteString("format:")
		for _, t := range project.SubTypes {
			b.WriteString(" format-" + string(t))
		}
		b.WriteString("\n")
	}

	b.WriteString("\n")
	b.WriteString("release: build\n")
	b.WriteString("\t@echo \"Release $(PROJECT_NAME) v$(VERSION)\"\n")
	b.WriteString("\n")
	b.WriteString("install: build\n")
	b.WriteString("\t@echo \"Install $(PROJECT_NAME)\"\n")
	b.WriteString("\n")
	b.WriteString("audit:\n")
	b.WriteString("\t@echo \"Audit $(PROJECT_NAME)\"\n")
	b.WriteString("\n")

	// Help
	b.WriteString("help:\n")
	b.WriteString("\t@echo \"$(PROJECT_NAME) - Makefile targets:\"\n")
	b.WriteString("\t@echo \"\"\n")
	b.WriteString("\t@echo \"  build    - Build the project\"\n")
	b.WriteString("\t@echo \"  test     - Run tests\"\n")
	b.WriteString("\t@echo \"  clean    - Clean build artifacts\"\n")
	b.WriteString("\t@echo \"  lint     - Run linters\"\n")
	b.WriteString("\t@echo \"  format   - Format code\"\n")
	b.WriteString("\t@echo \"  release  - Build release artifacts\"\n")
	b.WriteString("\t@echo \"  install  - Install the project\"\n")
	b.WriteString("\t@echo \"  audit    - Run security audit\"\n")
	b.WriteString("\t@echo \"  help     - Show this help\"\n")
	b.WriteString("\n")

	return b.String(), nil
}

func generateForType(t detect.Type, project *detect.Project) (string, error) {
	switch t {
	case detect.TypeGo:
		return goMakefile(project), nil
	case detect.TypeRust:
		return rustMakefile(project), nil
	case detect.TypePython:
		return pythonMakefile(project), nil
	case detect.TypeNode:
		return nodeMakefile(project), nil
	default:
		return "", fmt.Errorf("unsupported type: %s", t)
	}
}

func goMakefile(project *detect.Project) string {
	var b strings.Builder
	b.WriteString("# --- Go targets ---\n")

	// Detect binary name from module name or directory
	binName := project.Name
	if idx := strings.LastIndex(binName, "/"); idx >= 0 {
		binName = binName[idx+1:]
	}

	goVersion := project.Metadata["go_version"]

	b.WriteString(fmt.Sprintf("GO_BINARY ?= %s\n", sanitizeName(binName)))
	if goVersion != "" {
		b.WriteString(fmt.Sprintf("GO_VERSION ?= %s\n", goVersion))
	}
	b.WriteString("GO_BUILD_FLAGS ?= -ldflags=\"-s -w\"\n")
	b.WriteString("GO_TEST_FLAGS ?= -v -race -count=1\n")
	b.WriteString("GO_LINT_FLAGS ?= -c golangci-lint\n")
	b.WriteString("GO_PACKAGES ?= ./...\n")
	b.WriteString("\n")
	b.WriteString("build-go:\n")
	b.WriteString("\t@echo \"Building Go binary...\"\n")
	b.WriteString("\tgo build $(GO_BUILD_FLAGS) -o $(GO_BINARY) .\n")
	b.WriteString("\n")
	b.WriteString("test-go:\n")
	b.WriteString("\t@echo \"Running Go tests...\"\n")
	b.WriteString("\tgo test $(GO_TEST_FLAGS) $(GO_PACKAGES)\n")
	b.WriteString("\n")
	b.WriteString("clean-go:\n")
	b.WriteString("\t@echo \"Cleaning Go artifacts...\"\n")
	b.WriteString("\trm -f $(GO_BINARY)\n")
	b.WriteString("\tgo clean\n")
	b.WriteString("\n")
	b.WriteString("lint-go:\n")
	b.WriteString("\t@echo \"Linting Go code...\"\n")
	b.WriteString("\tgo vet $(GO_PACKAGES)\n")
	b.WriteString("\t@if command -v golangci-lint >/dev/null 2>&1; then golangci-lint run; fi\n")
	b.WriteString("\n")
	b.WriteString("format-go:\n")
	b.WriteString("\t@echo \"Formatting Go code...\"\n")
	b.WriteString("\tgo fmt $(GO_PACKAGES)\n")
	b.WriteString("\n")

	return b.String()
}

func rustMakefile(project *detect.Project) string {
	var b strings.Builder
	b.WriteString("# --- Rust targets ---\n")

	binName := sanitizeName(project.Name)
	if binName == "" {
		binName = "app"
	}

	b.WriteString(fmt.Sprintf("RUST_BINARY ?= %s\n", binName))
	b.WriteString("RUST_BUILD_FLAGS ?= --release\n")
	b.WriteString("RUST_TEST_FLAGS ?= -- --nocapture\n")
	b.WriteString("\n")
	b.WriteString("build-rust:\n")
	b.WriteString("\t@echo \"Building Rust project...\"\n")
	b.WriteString("\tcargo build $(RUST_BUILD_FLAGS)\n")
	b.WriteString("\n")
	b.WriteString("test-rust:\n")
	b.WriteString("\t@echo \"Running Rust tests...\"\n")
	b.WriteString("\tcargo test $(RUST_TEST_FLAGS)\n")
	b.WriteString("\n")
	b.WriteString("clean-rust:\n")
	b.WriteString("\t@echo \"Cleaning Rust artifacts...\"\n")
	b.WriteString("\tcargo clean\n")
	b.WriteString("\n")
	b.WriteString("lint-rust:\n")
	b.WriteString("\t@echo \"Linting Rust code...\"\n")
	b.WriteString("\tcargo check\n")
	b.WriteString("\t@if command -v clippy-driver >/dev/null 2>&1; then cargo clippy -- -D warnings; fi\n")
	b.WriteString("\n")
	b.WriteString("format-rust:\n")
	b.WriteString("\t@echo \"Formatting Rust code...\"\n")
	b.WriteString("\t@if command -v rustfmt >/dev/null 2>&1; then cargo fmt; fi\n")
	b.WriteString("\n")

	return b.String()
}

func pythonMakefile(project *detect.Project) string {
	var b strings.Builder
	b.WriteString("# --- Python targets ---\n")

	b.WriteString("PYTHON ?= python3\n")
	b.WriteString("PIP ?= pip3\n")
	b.WriteString("PYTEST_FLAGS ?= -v\n")
	b.WriteString("PYTHON_SRC ?= .\n")
	b.WriteString("\n")
	b.WriteString("build-python:\n")
	b.WriteString("\t@echo \"Building Python package...\"\n")
	b.WriteString("\t$(PYTHON) -m build\n")
	b.WriteString("\n")
	b.WriteString("test-python:\n")
	b.WriteString("\t@echo \"Running Python tests...\"\n")
	b.WriteString("\t$(PYTHON) -m pytest $(PYTEST_FLAGS)\n")
	b.WriteString("\n")
	b.WriteString("clean-python:\n")
	b.WriteString("\t@echo \"Cleaning Python artifacts...\"\n")
	b.WriteString("\trm -rf build/ dist/ *.egg-info/ __pycache__/ .pytest_cache/ .ruff_cache/\n")
	b.WriteString("\tfind . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true\n")
	b.WriteString("\n")
	b.WriteString("lint-python:\n")
	b.WriteString("\t@echo \"Linting Python code...\"\n")
	b.WriteString("\t@if command -v ruff >/dev/null 2>&1; then ruff check $(PYTHON_SRC); fi\n")
	b.WriteString("\t@if command -v mypy >/dev/null 2>&1; then mypy $(PYTHON_SRC); fi\n")
	b.WriteString("\n")
	b.WriteString("format-python:\n")
	b.WriteString("\t@echo \"Formatting Python code...\"\n")
	b.WriteString("\t@if command -v ruff >/dev/null 2>&1; then ruff format $(PYTHON_SRC); fi\n")
	b.WriteString("\n")

	return b.String()
}

func nodeMakefile(project *detect.Project) string {
	var b strings.Builder
	b.WriteString("# --- Node.js targets ---\n")

	b.WriteString("NODE ?= node\n")
	b.WriteString("NPM ?= npm\n")
	b.WriteString("NODE_TEST_FLAGS ?=\n")
	b.WriteString("\n")
	b.WriteString("build-node:\n")
	b.WriteString("\t@echo \"Building Node.js project...\"\n")
	b.WriteString("\t$(NPM) run build 2>/dev/null || $(NPM) run compile 2>/dev/null || echo \"No build script found\"\n")
	b.WriteString("\n")
	b.WriteString("test-node:\n")
	b.WriteString("\t@echo \"Running Node.js tests...\"\n")
	b.WriteString("\t$(NPM) test $(NODE_TEST_FLAGS) 2>/dev/null || $(NPM) run test 2>/dev/null || echo \"No test script found\"\n")
	b.WriteString("\n")
	b.WriteString("clean-node:\n")
	b.WriteString("\t@echo \"Cleaning Node.js artifacts...\"\n")
	b.WriteString("\trm -rf node_modules/ dist/ build/ .next/ coverage/\n")
	b.WriteString("\n")
	b.WriteString("lint-node:\n")
	b.WriteString("\t@echo \"Linting Node.js code...\"\n")
	b.WriteString("\t$(NPM) run lint 2>/dev/null || echo \"No lint script found\"\n")
	b.WriteString("\n")
	b.WriteString("format-node:\n")
	b.WriteString("\t@echo \"Formatting Node.js code...\"\n")
	b.WriteString("\t@if command -v prettier >/dev/null 2>&1; then prettier --write \"src/**/*.{js,ts,jsx,tsx,json,css}\"; fi\n")
	b.WriteString("\n")

	return b.String()
}

func sanitizeName(name string) string {
	// Extract last component if it's a module path
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		name = name[idx+1:]
	}
	// Replace non-alphanumeric chars with underscores
	var result strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-' {
			result.WriteRune(c)
		} else {
			result.WriteRune('_')
		}
	}
	return result.String()
}

func typeStrings(types []detect.Type) []string {
	out := make([]string, len(types))
	for i, t := range types {
		out[i] = string(t)
	}
	return out
}
